language: python
python:
  - "2.7"
script: nosetests xivo_ws
notifications:
  email:
    recipients:
      - dev+tests-reports@proformatique.com
    on_success: change
    on_failure: change
branches:
  only:
    - master
sudo: false
